spring:
  datasource:
    url: jdbc:h2:./dev;AUTO_SERVER=TRUE
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog.yml

  h2:
    console:
      enabled: true

logging:
  level:
    sql: debug
    web: debug
    kg.musabaev.megalabnews.service.impl: debug
