spring:
  datasource:
    url: jdbc:h2:./dev;AUTO_SERVER=TRUE
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog.yml

  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 1MB

logging:
  level:
    sql: debug
    web: debug
    kg.musabaev.megalabnews: debug
    org.springframework.cache: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs

app:
  cache-enabled: ${CACHE_ENABLED:false}
  storage:
    folder-name: ${STORAGE_FOLDER_NAME:storage}
    post-image-folder-name: ${POST_IMAGE_FOLDER_NAME:post-image}
    user-picture-folder-name: ${USER_PICTURE_FOLDER_NAME:user-picture}